export type { RoutingRule, RuleTarget, RuleSource, RuleTargetType, RuleAction } from './models/RoutingRule'
export type { RoutingPolicy, NormalizedPolicy, RoutingMode } from './models/RoutingPolicy'
export type { GeoRule, GeoCategory } from './models/GeoRule'
export type { SplitTunnelTarget, SplitTunnelRule, SplitTunnelPlatform } from './models/SplitTunnelTarget'
export type { ValidationResult, ValidationError, ValidationWarning } from './models/ValidationResult'
export { mergeValidationResults } from './models/ValidationResult'
export { emptyPolicy } from './models/RoutingPolicy'

export { PolicyNormalizer } from './pipeline/PolicyNormalizer'
export { PolicyValidator } from './pipeline/PolicyValidator'
export { PolicyOptimizer } from './pipeline/PolicyOptimizer'
export { RoutingPipeline } from './pipeline/RoutingPipeline'
export type { PipelineResult } from './pipeline/RoutingPipeline'

export type { RuleCompiler, CompiledOutput, CompilationMetadata } from './compiler/RuleCompiler'
export { MihomoRuleCompiler } from './compiler/MihomoRuleCompiler'
export type { MihomoCompilerOptions } from './compiler/MihomoRuleCompiler'

export type { RuleProvider, RuleProviderMetadata, RuleProviderType } from './providers/RuleProvider'
export { BundledRuleProvider } from './providers/BundledRuleProvider'
export { CacheRuleProvider } from './providers/CacheRuleProvider'
export { RemoteRuleProvider } from './providers/RemoteRuleProvider'
export type { RemoteRuleProviderConfig } from './providers/RemoteRuleProvider'
export { RuleProviderRegistry } from './providers/RuleProviderRegistry'

export { RUSSIA_BYPASS_RULES, RUSSIA_BYPASS_PRIVATE_DIRECT } from './data/bypass-rules'

export { createFullPolicy } from './policies/FullPolicy'
export { createBypassPolicy } from './policies/BypassPolicy'
export { createSplitPolicy } from './policies/SplitPolicy'
export { createCustomPolicy } from './policies/CustomPolicy'
export type { CustomPolicyConfig } from './policies/CustomPolicy'

export { RoutingManager } from './manager/RoutingManager'
export type { RoutingManagerConfig } from './manager/RoutingManager'
