import { randomUUID } from 'crypto'
import { Notification } from 'electron'
import { VPN, INITIAL_VPN_STATUS } from '@slave-vpn/shared'
import type { VPNStatus, VPNMode, VPNConnectionState } from '@slave-vpn/shared'
import { RuntimeManager } from '@slave-vpn/runtime'
import {
  diffConnectionProfiles,
  fingerprintConnectionProfile,
  safeLifecycleError,
} from '@slave-vpn/runtime'
import type { RuntimeState, HealthStatus, ConnectionProfile } from '@slave-vpn/runtime'
import type { ConfigSource } from '@slave-vpn/provider'
import type { DnsProfile } from '@slave-vpn/dns'
import type { RuntimeService } from '../RuntimeService'
import type {
  AppSettings,
  RuntimeEvent,
  RuntimeEventKind,
  RuntimeEventSeverity,
  VpnHealthPayload,
  VPNConnectivityInfo,
} from '../../../shared/ipc/types'
import { IpcChannel } from '../../../shared/ipc/channels'
import { sendToRenderer } from '../../window'
import { validateRuntimeEnvironment } from './RuntimeEnvironmentValidator'
import { getNodeHealthManager } from '../NodeHealthManager'
import { getConfigSourceService } from './ConfigSourceService'
import { getLogger } from '../../logger'
import { normalizeSubscriptionContent, parseProxiesFromYaml } from '@slave-vpn/config'
import { buildEngineDnsProfile, resolveDohUrl } from '../DnsProfileService'
import { getRoutingScenarioService } from '../RoutingScenarioService'
import { getSubscriptionStore } from '../SubscriptionStore'
import { getSubscriptionAggregator } from '../SubscriptionAggregatorService'
import { enableSystemProxy, disableSystemProxy } from './sources/WindowsSystemProxy'
import { classifyProxyFailure } from '@slave-vpn/core'
import type { ProxyFailureCode } from '@slave-vpn/core'

// ─── Mihomo API group names (generated by config package) ────────────────────
// config package uses SLAVE-SELECT; mihomoYaml.ts uses SLAVE — check both.
const SELECT_GROUP_CANDIDATES = ['SLAVE-SELECT', 'SLAVE']
const AUTO_GROUP = 'SLAVE-AUTO'

export type ConfigUpdateReason =
  | 'startup'
  | 'connect'
  | 'manual-subscription-refresh'
  | 'scheduled-subscription-refresh'
  | 'subscription-added'
  | 'subscription-removed'
  | 'subscription-enabled-change'
  | 'subscription-reordered'
  | 'profile-apply'
  | 'mode-change'
  | 'proxy-change'
  | 'resume'
  | 'recovery'
  | 'server-list-fallback'

const DEFAULT_GENERATOR_SETTINGS = {
  tunEnabled: true,
  tunStack: 'mixed' as const,
  fakeIpEnabled: true,
  dnsOverHttps: 'https://8.8.8.8/dns-query',
  fallbackDns: ['8.8.8.8', '8.8.4.4'],
  mixedPort: VPN.MIHOMO_MIXED_PORT,
}

// ─── Error classifier for Mihomo log output ───────────────────────────────────

const FAILURE_EVENT_KIND: Record<ProxyFailureCode, RuntimeEventKind> = {
  encryption: 'proxy.encryption_error',
  reality: 'proxy.reality_error',
  flow: 'proxy.flow_error',
  tls: 'proxy.tls_error',
  dns: 'proxy.dns_error',
  connection_refused: 'proxy.connection_refused',
  network_unreachable: 'proxy.network_unreachable',
  connection_reset: 'proxy.connection_reset',
  timeout: 'proxy.timeout',
  authentication: 'proxy.authentication_error',
  selector: 'proxy.selector_error',
  tun: 'vpn.preflight_failed',
}

function classifyMihomoLogLine_inner(line: string): { kind: RuntimeEventKind; userMessage: string } | null {
  const failure = classifyProxyFailure(line)
  return failure ? { kind: FAILURE_EVENT_KIND[failure.code], userMessage: failure.userMessage } : null
}

// ─── Health score ─────────────────────────────────────────────────────────────

function computeHealthScore(h: HealthStatus): number {
  if (!h.processAlive) return 0
  return (
    (h.processAlive   ? 25 : 0) +
    (h.apiResponding  ? 20 : 0) +
    (h.connectivityOk ? 20 : 0) +
    (h.dnsOk          ? 15 : 0) +
    (h.tunAvailable   ? 15 : 0) +
    (h.trafficActive  ? 5  : 0)
  )
}

// ─── State mapping ────────────────────────────────────────────────────────────

function engineStateToVpnState(state: RuntimeState): VPNConnectionState {
  switch (state) {
    case 'idle':         return 'disconnected'
    case 'starting':     return 'connecting'
    case 'running':      return 'connected'
    case 'stopping':     return 'disconnecting'
    case 'crashed':      return 'reconnecting'
    case 'reconnecting': return 'reconnecting'
    case 'error':        return 'error'
  }
}

// ─── Event factory ────────────────────────────────────────────────────────────

function makeEvent(
  kind: RuntimeEventKind,
  severity: RuntimeEventSeverity,
  message: string,
  metadata?: Record<string, unknown>
): RuntimeEvent {
  return {
    id: randomUUID(),
    kind,
    severity,
    timestamp: Date.now(),
    message,
    ...(metadata !== undefined ? { metadata } : {}),
  }
}

function classifyHealthDegradation(h: HealthStatus): RuntimeEventKind | null {
  if (!h.connectivityOk) return 'health.offline'
  if (!h.dnsOk) return 'health.dns_failure'
  if (!h.tunAvailable) return 'health.tunnel_unstable'
  const score = computeHealthScore(h)
  return score < 80 ? 'health.degraded' : null
}

// ─── Captive portal detection ─────────────────────────────────────────────────
// Passive: fires only when connectivity is already broken (no extra polling).

async function detectCaptivePortal(): Promise<boolean> {
  try {
    const res = await fetch('http://connectivitycheck.gstatic.com/generate_204', {
      method: 'GET',
      signal: AbortSignal.timeout(3000),
      redirect: 'manual',
    })
    // 204 = internet is working; anything else (redirect/200/etc.) = captive portal
    return res.status !== 204
  } catch {
    return false  // can't tell — assume no captive portal
  }
}

function buildSuggestion(
  h: HealthStatus,
  captivePortal: boolean | undefined,
  quarantinedNodes: number
): string | null {
  if (captivePortal) return 'Обнаружен captive portal — подключитесь к сети через браузер'
  if (!h.dnsOk) return 'DNS не работает — попробуйте сменить DNS-профиль'
  if (!h.tunAvailable) return 'TUN-адаптер недоступен — перезапустите приложение от имени администратора'
  if (quarantinedNodes > 0) return `${quarantinedNodes} узлов в карантине — попробуйте другой прокси`
  if (!h.connectivityOk) return 'Нет связи с сервером — проверьте настройки прокси или смените узел'
  return null
}

// ─── Config ───────────────────────────────────────────────────────────────────

export interface RuntimeServiceConfig {
  manager: RuntimeManager
  configSource?: ConfigSource
  getSettings: () => AppSettings
  apiPort?: number
  apiSecret?: string
  binaryPath?: string
  workingDir?: string
  setSettings?: (patch: Partial<AppSettings>) => void | Promise<void>
  waitForSettings?: () => Promise<AppSettings>
}

// ─── Implementation ───────────────────────────────────────────────────────────

export class RuntimeServiceImpl implements RuntimeService {
  private readonly manager: RuntimeManager
  private configSource: ConfigSource | undefined
  private readonly getSettings: () => AppSettings
  private readonly apiPort: number
  private readonly apiSecret: string
  private readonly binaryPath: string
  private readonly workingDir: string
  private readonly setSettings: (patch: Partial<AppSettings>) => void | Promise<void>
  private readonly waitForSettings: () => Promise<AppSettings>

  private currentMode: VPNMode = 'blocked'
  private connectedAt: number | null = null
  private lastError: string | null = null
  private lastHealthDegradation: RuntimeEventKind | null = null
  private activeProxy: string | null = null
  private configOperationId = 0
  private profileResolutionTail: Promise<void> = Promise.resolve()
  private connectionEpoch = 0
  private selectionRevision = 0
  private modeRevision = 0
  private discoveryRevision = 0

  // Throttle error classification — don't spam the same error every log line
  private lastClassifiedErrorKind: string | null = null
  private lastClassifiedAt = 0

  // Mutex flags: prevent concurrent connect/disconnect operations
  private connectLock = false
  private disconnectLock = false

  setConfigSource(source: ConfigSource): void {
    this.configSource = source
  }

  constructor(config: RuntimeServiceConfig) {
    this.manager = config.manager
    this.configSource = config.configSource
    this.getSettings = config.getSettings
    this.apiPort = config.apiPort ?? VPN.MIHOMO_API_PORT
    this.apiSecret = config.apiSecret ?? ''
    this.binaryPath = config.binaryPath ?? ''
    this.workingDir = config.workingDir ?? ''
    this.setSettings = config.setSettings ?? (() => undefined)
    this.waitForSettings = config.waitForSettings ?? (() => Promise.resolve(this.getSettings()))

    this.manager.on('stateChanged', ({ state }) => {
      getLogger().info({ state, connectionDesired: this.manager.isConnectionDesired(),
        generation: this.connectionEpoch }, 'runtime.state.changed')
      if (state === 'running') {
        this.connectedAt = Date.now()
        this.lastError = null
        this.lastClassifiedErrorKind = null
        enableSystemProxy('127.0.0.1', VPN.MIHOMO_MIXED_PORT)
        sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
          makeEvent('vpn.connected', 'info', 'VPN connected'))
        this.notifyOs('SLAVE VPN', 'Подключено')
        // Async: discover active proxy after engine is up
        this.refreshActiveProxy().catch(() => undefined)
        // Record success for active proxy
        if (this.activeProxy) {
          getNodeHealthManager().recordSuccess(this.activeProxy)
        }
      } else if (state === 'idle') {
        const wasConnected = this.connectedAt !== null
        this.connectedAt = null
        this.activeProxy = null
        disableSystemProxy()
        if (wasConnected) {
          sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
            makeEvent('vpn.disconnected', 'info', 'VPN disconnected'))
          this.notifyOs('SLAVE VPN', 'Отключено')
        }
      } else if (state === 'error') {
        this.connectedAt = null
        this.activeProxy = null
        sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
          makeEvent('vpn.error', 'error', this.lastError ?? 'VPN error'))
        this.notifyOs('SLAVE VPN — ошибка', this.lastError ?? 'Ошибка подключения')
      } else if (state === 'reconnecting' || state === 'crashed') {
        sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
          makeEvent('reconnect.attempt', 'warning', 'Attempting reconnect', { state }))
      }
      sendToRenderer(IpcChannel.EVENT_VPN_STATUS, this.getStatus())
    })

    this.manager.on('trafficUpdate', ({ stats }) => {
      sendToRenderer(IpcChannel.EVENT_VPN_TRAFFIC, stats)
    })

    this.manager.on('error', ({ error, fatal }) => {
      this.lastError = error.message
      if (fatal) {
        sendToRenderer(IpcChannel.EVENT_VPN_ERROR, {
          code: 'FATAL_ENGINE_ERROR',
          message: error.message,
        })
        sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
          makeEvent('vpn.error', 'critical', error.message, { fatal: true }))
      }
    })

    this.manager.on('healthChanged', ({ health }) => {
      const payload: VpnHealthPayload = {
        processAlive: health.processAlive,
        apiResponding: health.apiResponding,
        connectivityOk: health.connectivityOk,
        dnsOk: health.dnsOk,
        trafficActive: health.trafficActive,
        tunAvailable: health.tunAvailable,
        checkedAt: health.checkedAt,
      }
      sendToRenderer(IpcChannel.EVENT_VPN_HEALTH, payload)

      const degradationKind = classifyHealthDegradation(health)
      if (degradationKind !== this.lastHealthDegradation) {
        if (degradationKind !== null) {
          sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
            makeEvent(degradationKind, 'warning', `Connection health degraded: ${degradationKind}`))
        } else if (this.lastHealthDegradation !== null) {
          sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
            makeEvent('health.recovered', 'info', 'Connection health recovered'))
        }
        this.lastHealthDegradation = degradationKind
      }
    })

    // Subscribe to Mihomo log output: forward to pino + classify for IPC events.
    // ProcessManager now parses the actual Mihomo level from the structured log line.
    this.manager.on('logLine', ({ level, message }) => {
      if (level === 'error') {
        getLogger().error({ from: 'mihomo' }, message)
      } else if (level === 'warn') {
        getLogger().warn({ from: 'mihomo' }, message)
      } else if (level === 'info') {
        getLogger().info({ from: 'mihomo' }, message)
      } else {
        return  // drop debug/trace
      }

      const classified = classifyMihomoLogLine_inner(message)
      if (!classified) return

      const now = Date.now()
      const isDuplicate =
        classified.kind === this.lastClassifiedErrorKind &&
        now - this.lastClassifiedAt < 10_000

      if (!isDuplicate) {
        this.lastClassifiedErrorKind = classified.kind
        this.lastClassifiedAt = now
        sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
          makeEvent(classified.kind, 'warning', classified.userMessage))

        // Record failure against the active proxy for node health tracking
        if (this.activeProxy) {
          getNodeHealthManager().recordFailure(this.activeProxy, classified.kind)
        }
      }
    })
  }

  // ── OS notifications ───────────────────────────────────────────────────────
  // Show a native desktop notification for connect/disconnect/error, gated by the
  // «Уведомления» setting. Before this the toggle existed in the UI but nothing
  // read it and no OS notification was ever emitted — a dead switch. Fully
  // guarded (isSupported + settings) so a headless/unsupported host is a no-op.
  private notifyOs(title: string, body: string): void {
    try {
      if (!this.getSettings().notificationsEnabled) return
      if (!Notification.isSupported()) return
      new Notification({ title, body, silent: false }).show()
    } catch {
      // Never let a notification failure affect the connection lifecycle.
    }
  }

  // ── Pre-flight validation ──────────────────────────────────────────────────

  private async runPreflight(): Promise<void> {
    if (!this.binaryPath) return  // skip if path not configured (dev/test)

    const result = await validateRuntimeEnvironment({
      binaryPath: this.binaryPath,
      workingDir: this.workingDir,
      apiPort: this.apiPort,
    })

    const log = getLogger()

    for (const issue of result.issues) {
      log.warn({ code: issue.code }, `Preflight: ${issue.message}`)
      const severity: RuntimeEventSeverity = issue.fatal ? 'error' : 'warning'
      const kind: RuntimeEventKind = issue.fatal ? 'vpn.preflight_failed' : 'vpn.preflight_warn'
      sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
        makeEvent(kind, severity, issue.message, { code: issue.code }))
    }

    if (!result.ok) {
      const fatal = result.issues.find(i => i.fatal)
      throw new Error(fatal?.message ?? 'Runtime environment validation failed')
    }
  }

  // ── Engine profile composition (DNS + routing) ─────────────────────────────
  // Build the DnsProfile from current settings. RoutingPolicy is composed
  // later via RoutingScenarioService (A.3); for now returns undefined and
  // the engine falls back to legacy vpnMode-based rules.

  private buildDnsProfileForEngine(settings: AppSettings): DnsProfile {
    // Unified DoH provider (shared with Android): override the preset's primary
    // DoH endpoint with the user's chosen provider. undefined → preset default.
    const dohOverrideUrl = settings.dohProvider
      ? resolveDohUrl(settings.dohProvider)
      : undefined
    const profile = buildEngineDnsProfile(
      settings.dnsPreset,
      settings.customDnsProfile,
      settings.dnsStrategy,
      dohOverrideUrl,
    )
    // «Свои правила» → напрямую: exclude those domains from fake-ip so they
    // resolve to REAL IPs — under fake-ip a DIRECT rule would otherwise hand the
    // app a synthetic 198.18.x address (the same anti-fraud problem the curated
    // bank list solves). Suffix rules → `+.domain`, exact → bare domain.
    const directDomains = (settings.customRoutingRules ?? [])
      .filter((r) => r.action === 'direct')
      .map((r) => (r.matchType === 'suffix' ? `+.${r.domain}` : r.domain))
    if (directDomains.length === 0 || !profile.fakeIp.enabled) return profile
    return {
      ...profile,
      fakeIp: { ...profile.fakeIp, filter: [...(profile.fakeIp.filter ?? []), ...directDomains] },
    }
  }

  // ── Subscription resolution (aggregator-first, legacy fallback) ────────────

  private async fetchSubscriptionYaml(checkFreshness = false): Promise<{
    yaml: string
    proxyCount: number
    source: 'aggregator' | 'configSource'
    snapshotRevision?: number
    snapshotHash?: string
  }> {
    const log = getLogger()
    const enabled = getSubscriptionStore().list().filter(e => e.enabled)

    if (enabled.length > 0 || this.configSource) {
      try {
        const snapshot = await getSubscriptionAggregator().getSnapshotOrFetch(checkFreshness)
        for (const w of snapshot.warnings) log.warn({ source: 'aggregator' }, w)
        return {
          yaml: snapshot.yaml,
          proxyCount: snapshot.totalProxies,
          source: 'aggregator',
          snapshotRevision: snapshot.revision,
          snapshotHash: snapshot.hash,
        }
      } catch (err) {
        log.warn({ err }, 'Aggregator failed — falling back to legacy configSource')
      }
    }

    if (this.configSource) {
      const yaml = await this.configSource.fetchYaml()
      let proxyCount = 0
      try { proxyCount = normalizeSubscriptionContent(yaml).proxyCount } catch { /* keep 0 */ }
      return { yaml, proxyCount, source: 'configSource' }
    }

    throw new Error('No subscription configured — add one in Подписки tab or complete onboarding')
  }

  private buildDesiredProfile(subscriptionYaml: string, settings: AppSettings): ConnectionProfile {
    const mode = settings.vpnMode
    const desiredSelectedProxy = settings.selectedProxy ?? undefined
    const routingPolicy = getRoutingScenarioService().composePolicyForMode(mode, settings) ?? undefined
    return {
      subscriptionYaml,
      vpnMode: mode,
      ...(desiredSelectedProxy ? { selectedProxy: desiredSelectedProxy } : {}),
      generatorSettings: {
        ...DEFAULT_GENERATOR_SETTINGS,
        ...(mode === 'split' ? { splitTunnelProcesses: settings.splitProcessList ?? [] } : {}),
      },
      dnsProfile: this.buildDnsProfileForEngine(settings),
      ...(routingPolicy ? { routingPolicy } : {}),
      utlsFingerprint: settings.utlsFingerprint ?? 'randomized',
    }
  }

  private resolveAvailableSelection(subscriptionYaml: string, settings: AppSettings): {
    settings: AppSettings
    unavailableSelection: string | null
  } {
    const selectedProxy = settings.selectedProxy?.trim()
    if (!selectedProxy || selectedProxy === AUTO_GROUP) {
      return { settings, unavailableSelection: null }
    }

    try {
      const proxies = parseProxiesFromYaml(subscriptionYaml)
      // Stay conservative if the source cannot provide positive node evidence.
      // The generated SLAVE-AUTO group is not part of the subscription YAML and
      // is handled above as an always-valid selection.
      if (proxies.length === 0 || proxies.some(proxy => proxy.name === selectedProxy)) {
        return { settings, unavailableSelection: null }
      }
    } catch {
      return { settings, unavailableSelection: null }
    }

    return {
      settings: { ...settings, selectedProxy: AUTO_GROUP },
      unavailableSelection: selectedProxy,
    }
  }

  private async persistUnavailableSelectionFallback(
    unavailableSelection: string | null,
    selection: number,
    epoch: number,
  ): Promise<void> {
    if (!unavailableSelection || selection !== this.selectionRevision ||
      epoch !== this.connectionEpoch || this.manager.getState() !== 'running' ||
      this.getSettings().selectedProxy !== unavailableSelection) return

    await this.setSettings({ selectedProxy: AUTO_GROUP })
    const settings = await this.waitForSettings()
    if (selection !== this.selectionRevision || epoch !== this.connectionEpoch ||
      this.manager.getState() !== 'running' || settings.selectedProxy !== AUTO_GROUP) return

    ++this.selectionRevision
    this.activeProxy = null
    getLogger().warn('runtime.saved_proxy_unavailable: saved server is absent; selection reset to AUTO')
    sendToRenderer(IpcChannel.EVENT_VPN_STATUS, this.getStatus())
    sendToRenderer(IpcChannel.EVENT_PROXY_CHANGED, AUTO_GROUP)
    sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
      makeEvent('proxy.selected', 'warning', 'Saved server is unavailable; switched to AUTO'))
    void this.refreshActiveProxy().catch(() => undefined)
  }

  private async applyDesiredProfile(reason: ConfigUpdateReason): Promise<void> {
    const epoch = this.connectionEpoch
    const operation = this.profileResolutionTail.then(async () => {
      await this.waitForSettings()
      if (epoch !== this.connectionEpoch || this.manager.getState() !== 'running') return
      await this.resolveAndApplyProfile(reason, epoch)
    })
    this.profileResolutionTail = operation.catch(() => undefined)
    return operation
  }

  private async resolveAndApplyProfile(reason: ConfigUpdateReason, epoch: number): Promise<void> {
    const operationId = ++this.configOperationId
    const resolved = await this.fetchSubscriptionYaml()
    const settings = await this.waitForSettings()
    if (epoch !== this.connectionEpoch || this.manager.getState() !== 'running') return
    this.currentMode = settings.vpnMode
    if (resolved.proxyCount === 0) {
      getLogger().warn({ operationId, reason, source: resolved.source }, 'config-update skipped: empty proxy list')
      return
    }

    const previous = this.manager.getCurrentProfile()
    const selection = this.selectionRevision
    const available = this.resolveAvailableSelection(resolved.yaml, settings)
    const next = this.buildDesiredProfile(resolved.yaml, available.settings)
    const previousHash = previous ? fingerprintConnectionProfile(previous) : null
    const nextHash = fingerprintConnectionProfile(next)
    const common = {
      operationId,
      reason,
      source: resolved.source,
      snapshotRevision: resolved.snapshotRevision,
      snapshotHash: resolved.snapshotHash?.slice(0, 12),
      previousProfileHash: previousHash?.slice(0, 12),
      nextProfileHash: nextHash.slice(0, 12),
      profileDiff: diffConnectionProfiles(previous, next),
      vpnMode: this.currentMode,
      desiredSelectedProxy: settings.selectedProxy ?? null,
      observedActiveProxy: this.activeProxy,
    }
    getLogger().info(common, 'config-update requested')
    const reloadType = await this.manager.updateProfile(next)
    await this.persistUnavailableSelectionFallback(available.unavailableSelection, selection, epoch)
    getLogger().info({
      ...common,
      reloadType,
      decision: reloadType === 'none' ? 'skip-identical' : 'applied',
    }, 'config-update completed')
  }

  // ── Active proxy discovery ─────────────────────────────────────────────────

  private async refreshActiveProxy(): Promise<void> {
    if (!this.apiSecret || this.manager.getState() !== 'running') return
    const epoch = this.connectionEpoch
    const selection = this.selectionRevision
    const discovery = ++this.discoveryRevision
    const isCurrent = () => epoch === this.connectionEpoch &&
      selection === this.selectionRevision && discovery === this.discoveryRevision &&
      this.manager.getState() === 'running'

    for (const group of SELECT_GROUP_CANDIDATES) {
      try {
        const res = await fetch(
          `http://127.0.0.1:${this.apiPort}/proxies/${encodeURIComponent(group)}`,
          {
            headers: { Authorization: `Bearer ${this.apiSecret}` },
            signal: AbortSignal.timeout(3000),
          }
        )
        if (!res.ok) continue
        const data = await res.json() as { now?: string }
        if (!isCurrent()) return
        if (data.now) {
          this.activeProxy = data.now
          sendToRenderer(IpcChannel.EVENT_VPN_STATUS, this.getStatus())
          sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
            makeEvent('proxy.selected', 'info', `Active proxy: ${data.now}`))
          return
        }
      } catch { /* try next group */ }
      if (!isCurrent()) return
    }
  }

  // ── Public API ─────────────────────────────────────────────────────────────

  async connect(): Promise<void> {
    const state = this.manager.getState()
    if (state === 'running') return  // idempotent: already connected
    if (state === 'starting' || this.connectLock) {
      throw new Error('Connection already in progress')
    }

    // Either legacy configSource OR multi-subscription store must have something usable.
    const hasMultiSub = getSubscriptionStore().list().some(e => e.enabled)
    if (!this.configSource && !hasMultiSub) {
      throw new Error('No subscription configured. Add one in Подписки или complete onboarding.')
    }

    this.connectLock = true
    const epoch = ++this.connectionEpoch
    const log = getLogger()
    try {
      log.info({ generation: epoch, state, connectionDesired: this.manager.isConnectionDesired() }, 'runtime.connect.begin')
      await this.runPreflight()
      await this.waitForSettings()

      const { yaml: subscriptionYaml, proxyCount, source, snapshotRevision, snapshotHash } = await this.fetchSubscriptionYaml(true)
      const settings = await this.waitForSettings()
      if (epoch !== this.connectionEpoch) return
      this.currentMode = settings.vpnMode

      if (proxyCount === 0) {
        const msg = 'Subscription has no usable proxies. Check your config source in settings.'
        sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
          makeEvent('vpn.preflight_failed', 'error', msg, { code: 'NO_PROXIES' }))
        throw new Error(msg)
      }

      log.info({ proxyCount, source }, 'Subscription resolved before connect')

      const selection = this.selectionRevision
      const available = this.resolveAvailableSelection(subscriptionYaml, settings)
      const profile = this.buildDesiredProfile(subscriptionYaml, available.settings)
      const operationId = ++this.configOperationId
      log.info({
        operationId,
        reason: 'connect',
        source,
        snapshotRevision,
        snapshotHash: snapshotHash?.slice(0, 12),
        nextProfileHash: fingerprintConnectionProfile(profile).slice(0, 12),
        vpnMode: profile.vpnMode,
        desiredSelectedProxy: settings.selectedProxy ?? null,
        observedActiveProxy: this.activeProxy,
      }, 'config-update requested')
      await this.manager.connect(profile)
      await this.persistUnavailableSelectionFallback(available.unavailableSelection, selection, epoch)
      log.info({ operationId, reason: 'connect', decision: 'engine-start' }, 'config-update completed')
    } catch (error) {
      const failure = safeLifecycleError(error)
      this.lastError = failure.errorMessage
      log.warn({ ...failure, generation: epoch, state: this.manager.getState(),
        connectionDesired: this.manager.isConnectionDesired() }, `runtime.connect.failed: ${failure.errorMessage}`)
      throw error
    } finally {
      this.connectLock = false
    }
  }

  async disconnect(): Promise<void> {
    ++this.connectionEpoch
    if (this.disconnectLock) return  // already disconnecting
    this.disconnectLock = true
    try {
      await this.manager.disconnect('intentional')
    } finally {
      this.disconnectLock = false
    }
  }

  async reconnectAfterResume(): Promise<void> {
    if (this.manager.getState() !== 'running' || !this.manager.isConnectionDesired() ||
        this.connectLock || this.disconnectLock) return
    const epoch = this.connectionEpoch + 1
    await this.disconnect()
    // A user command during shutdown supersedes the resume request.
    if (epoch !== this.connectionEpoch) return
    await this.connect()
  }

  getStatus(): VPNStatus {
    const state = this.manager.getState()
    const health = this.manager.getHealth()
    return {
      ...INITIAL_VPN_STATUS,
      state: engineStateToVpnState(state),
      mode: this.currentMode,
      connectedAt: this.connectedAt,
      lastError: this.lastError,
      ...(this.activeProxy ? { activeProxy: this.activeProxy } : {}),
      ...(health.checkedAt ? { engineHealthScore: computeHealthScore(health) } : {}),
    }
  }

  async setMode(mode: VPNMode): Promise<void> {
    const revision = ++this.modeRevision
    const epoch = this.connectionEpoch
    await this.setSettings({ vpnMode: mode })
    const settings = await this.waitForSettings()
    if (revision !== this.modeRevision || epoch !== this.connectionEpoch) return
    this.currentMode = settings.vpnMode

    if (this.manager.getState() === 'running') {
      await this.applyDesiredProfile('mode-change')
    }
  }

  getEngineVersion(): string | null {
    return this.manager.getEngineVersion()
  }

  async getConnectivity(): Promise<VPNConnectivityInfo | null> {
    const epoch = this.connectionEpoch
    const selectionRevision = this.selectionRevision
    const profileHash = this.manager.getCurrentProfileHash()
    const state = this.manager.getState()
    const health = this.manager.getHealth()

    let activeProxy: string | null = this.activeProxy
    let proxyCount = 0

    if (state === 'running' && health.apiResponding && this.apiSecret) {
      // Refresh active proxy
      for (const group of SELECT_GROUP_CANDIDATES) {
        try {
          const res = await fetch(
            `http://127.0.0.1:${this.apiPort}/proxies/${encodeURIComponent(group)}`,
            {
              headers: { Authorization: `Bearer ${this.apiSecret}` },
              signal: AbortSignal.timeout(3000),
            }
          )
          if (!res.ok) continue
          const data = await res.json() as { now?: string; all?: string[] }
          if (data.now) activeProxy = data.now
          if (data.all) proxyCount = data.all.length
          break
        } catch { /* try next */ }
      }
    }

    // Captive portal detection: check for redirect on plain HTTP
    let captivePortal: boolean | undefined
    if (state === 'running' && !health.connectivityOk) {
      captivePortal = await detectCaptivePortal()
    }

    const quarantinedNodes = getNodeHealthManager().getQuarantinedNodes().length
    const healthScore = computeHealthScore(health)

    const suggestion = buildSuggestion(health, captivePortal, quarantinedNodes)

    // Determine Reality/TLS status for the active proxy
    let realityStatus: 'reality' | 'tls' | 'none' = 'none'
    if (activeProxy && state === 'running') {
      try {
        const entries = await getConfigSourceService().getServerList()
        const entry = entries.find(e => e.name === activeProxy)
        if (entry?.securityType === 'reality') realityStatus = 'reality'
        else if (entry?.securityType === 'tls') realityStatus = 'tls'
      } catch { /* non-fatal */ }
    }

    const apiUrl = state === 'running' ? `http://127.0.0.1:${this.apiPort}` : undefined

    if (epoch !== this.connectionEpoch || selectionRevision !== this.selectionRevision ||
      state !== this.manager.getState() || profileHash !== this.manager.getCurrentProfileHash()) return null

    return {
      engineState: state,
      processAlive: health.processAlive,
      apiResponding: health.apiResponding,
      tunAvailable: health.tunAvailable,
      connectivityOk: health.connectivityOk,
      dnsOk: health.dnsOk,
      trafficActive: health.trafficActive,
      activeProxy,
      proxyCount,
      healthScore,
      checkedAt: health.checkedAt > 0 ? health.checkedAt : Date.now(),
      ...(captivePortal !== undefined ? { captivePortal } : {}),
      ...(quarantinedNodes > 0 ? { quarantinedNodes } : {}),
      ...(suggestion ? { suggestion } : {}),
      realityStatus,
      ...(apiUrl ? { apiUrl } : {}),
    }
  }

  getState(): string {
    return this.manager.getState()
  }

  async probeProxyLatency(tag: string, testUrl: string, timeoutMs: number): Promise<number | null> {
    if (this.manager.getState() !== 'running') return null
    return this.manager.probeLatency(tag, testUrl, timeoutMs)
  }

  async setSelectedProxy(proxyName: string): Promise<void> {
    if (this.manager.getState() !== 'running') {
      throw new Error('Cannot change proxy: VPN is not running')
    }

    // Persist intent before queueing the engine mutation so a concurrent refresh
    // cannot rebuild from a stale observed leaf. AUTO remains the desired group.
    const previousProxy = this.getSettings().selectedProxy ?? null
    const selection = ++this.selectionRevision
    const epoch = this.connectionEpoch
    await this.setSettings({ selectedProxy: proxyName })
    await this.waitForSettings()
    if (selection !== this.selectionRevision || epoch !== this.connectionEpoch ||
      this.manager.getState() !== 'running') return
    try {
      await this.applyDesiredProfile('proxy-change')
    } catch (error) {
      // MihomoEngine has already restored its previous applied profile. Restore
      // the persisted intent as well; otherwise the rejected node poisons every
      // later mode/subscription refresh and the UI lies after restart.
      if (selection === this.selectionRevision && epoch === this.connectionEpoch &&
        this.manager.getState() === 'running' && this.getSettings().selectedProxy === proxyName) {
        try {
          await this.setSettings({ selectedProxy: previousProxy })
          await this.waitForSettings()
        } catch (rollbackError) {
          getLogger().error({ rollbackError }, 'Proxy selection settings rollback failed')
          throw new Error('Proxy selection failed and its saved setting could not be restored')
        }
      }
      throw error
    }
    if (selection !== this.selectionRevision || epoch !== this.connectionEpoch ||
      this.manager.getState() !== 'running' || this.getSettings().selectedProxy !== proxyName) return
    if (proxyName === AUTO_GROUP) {
      this.activeProxy = null
      void this.refreshActiveProxy().catch(() => undefined)
    } else {
      this.activeProxy = proxyName
    }
    sendToRenderer(IpcChannel.EVENT_VPN_STATUS, this.getStatus())
    sendToRenderer(IpcChannel.EVENT_PROXY_CHANGED, proxyName)
    sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
      makeEvent('proxy.selected', 'info', `Proxy changed to: ${proxyName}`))
  }

  // Called by SubscriptionsHandler after add/update/remove/refresh while VPN is running.
  // Triggers a hot-reload through manager.updateProfile so the engine picks up the
  // newly aggregated YAML. No-op when disconnected.
  async notifySubscriptionsChanged(reason: ConfigUpdateReason = 'manual-subscription-refresh'): Promise<void> {
    if (reason === 'profile-apply') { ++this.selectionRevision; ++this.modeRevision }
    if (this.manager.getState() !== 'running') return
    const log = getLogger()
    try {
      await this.applyDesiredProfile(reason)
    } catch (err) {
      log.warn({ err, reason }, 'Subscription hot-reload failed')
      // Surface the failure to the UI diagnostics journal — a silent
      // warn-log meant the user never learned the running tunnel kept the
      // previous node list after a subscription refresh.
      sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
        makeEvent('subscriptions.reload_failed', 'error',
          `Не удалось применить обновлённые подписки к активному подключению: ${err instanceof Error ? err.message : String(err)}`,
          { reason }))
      if (reason === 'profile-apply') throw err
    }
  }

  // ── Active connections (Mihomo /connections) ──────────────────────────────

  async getConnections(): Promise<import('../../../shared/ipc/types').ActiveConnectionsSnapshot | null> {
    const info = await this.manager.getConnections()
    if (!info) return null

    const connections = info.connections.map(c => {
      const meta = c.metadata
      const chain = c.chains[0] ?? 'DIRECT'  // mihomo prepends final hop
      const process = meta.process ?? (meta.processPath ? meta.processPath.split(/[\\/]/).pop() : undefined)
      return {
        id: c.id,
        host: meta.host || meta.destinationIP || '—',
        network: meta.network ?? 'tcp',
        type: meta.type ?? '',
        destinationIP: meta.destinationIP ?? '',
        destinationPort: meta.destinationPort ?? '',
        sourceIP: meta.sourceIP ?? '',
        sourcePort: meta.sourcePort ?? '',
        ...(process ? { process } : {}),
        chain,
        rule: c.rule ?? '',
        upload: c.upload,
        download: c.download,
        start: c.start,
      }
    })

    return {
      uploadTotal: info.uploadTotal,
      downloadTotal: info.downloadTotal,
      count: connections.length,
      connections,
      fetchedAt: Date.now(),
    }
  }

  async closeConnection(id: string): Promise<void> {
    await this.manager.closeConnection(id)
  }

  async getProxyList(): Promise<import('../../../shared/ipc/types').ProxyEntry[]> {
    const enabled = getSubscriptionStore().list().some(entry => entry.enabled)
    if (enabled) {
      try {
        // Keep the dashboard projection identical to the configuration applied
        // to Mihomo. The legacy ConfigSource can be retained after migration and
        // is not a valid UI source of truth once SubscriptionStore is active.
        const snapshot = await getSubscriptionAggregator().getSnapshotOrFetch()
        return parseProxiesFromYaml(snapshot.yaml).map(entry => ({
          name: entry.name,
          type: entry.type,
          server: entry.server,
          port: entry.port,
          ...(entry.transport ? { transport: entry.transport } : {}),
          ...(entry.securityType ? { security: entry.securityType } : {}),
        }))
      } catch (error) {
        getLogger().warn({ error }, 'Aggregated dashboard proxy list failed; using legacy source')
      }
    }
    try {
      const entries = await getConfigSourceService().getServerList()
      return entries.map(e => ({
        name: e.name,
        type: e.proxyProtocol,
        server: e.server,
        ...(e.port !== undefined ? { port: e.port } : {}),
        ...(e.transport ? { transport: e.transport } : {}),
        ...(e.securityType ? { security: e.securityType } : {}),
      }))
    } catch {
      return []
    }
  }

  dispose(): Promise<void> {
    ++this.connectionEpoch
    return this.manager.dispose()
  }
}
