import { randomUUID } from 'crypto'
import { VPN, INITIAL_VPN_STATUS } from '@slave-vpn/shared'
import type { VPNStatus, VPNMode, VPNConnectionState } from '@slave-vpn/shared'
import { RuntimeManager } from '@slave-vpn/runtime'
import type { RuntimeState, HealthStatus } from '@slave-vpn/runtime'
import type { ConfigSource } from '@slave-vpn/provider'
import type { DnsProfile } from '@slave-vpn/dns'
import type { NormalizedPolicy } from '@slave-vpn/routing'
import type { RuntimeService } from '../RuntimeService'
import type {
  AppSettings,
  RuntimeEvent,
  RuntimeEventKind,
  RuntimeEventSeverity,
  VpnHealthPayload,
  VPNConnectivityInfo,
} from '../../../shared/ipc/types'
import { IpcChannel } from '../../../shared/ipc/channels'
import { sendToRenderer } from '../../window'
import { validateRuntimeEnvironment } from './RuntimeEnvironmentValidator'
import { getNodeHealthManager } from '../NodeHealthManager'
import { getConfigSourceService } from './ConfigSourceService'
import { getLogger } from '../../logger'
import { normalizeSubscriptionContent } from '@slave-vpn/config'
import { buildEngineDnsProfile } from '../DnsProfileService'
import { getRoutingScenarioService } from '../RoutingScenarioService'
import { getSubscriptionStore } from '../SubscriptionStore'
import { getSubscriptionAggregator } from '../SubscriptionAggregatorService'
import { enableSystemProxy, disableSystemProxy } from './sources/WindowsSystemProxy'

// ─── Mihomo API group names (generated by config package) ────────────────────
// config package uses SLAVE-SELECT; mihomoYaml.ts uses SLAVE — check both.
const SELECT_GROUP_CANDIDATES = ['SLAVE-SELECT', 'SLAVE']

const DEFAULT_GENERATOR_SETTINGS = {
  tunEnabled: true,
  tunStack: 'mixed' as const,
  fakeIpEnabled: true,
  dnsOverHttps: 'https://8.8.8.8/dns-query',
  fallbackDns: ['8.8.8.8', '8.8.4.4'],
  mixedPort: VPN.MIHOMO_MIXED_PORT,
}

// ─── Error classifier for Mihomo log output ───────────────────────────────────

function classifyMihomoLogLine_inner(line: string): { kind: RuntimeEventKind; userMessage: string } | null {
  const lower = line.toLowerCase()

  // VLESS Encryption (ML-KEM-768 / X25519) — checked FIRST so an enc/key/mode
  // problem is reported as a CRYPTO issue (keys/mode), distinct from a network
  // failure (refused/timeout). Patterns are mihomo's actual log strings:
  //   "failed to use encryption: empty nfsPKeysBytes"  (key empty/truncated)
  //   "invaild vless encryption value: ..."            (mihomo's typo; bad mode)
  if (lower.includes('nfspkeys') ||
      (lower.includes('encryption') && (lower.includes('vless') || lower.includes('nfs'))) ||
      lower.includes('vless encryption value')) {
    return {
      kind: 'proxy.encryption_error',
      userMessage:
        'Ошибка VLESS Encryption — ключ/режим не приняты ядром. Проверьте ' +
        'строку encryption в подписке (режим mlkem768x25519plus, appearance, ' +
        'rtt и полный ключ ML-KEM).',
    }
  }

  if ((lower.includes('reality') || lower.includes('utls')) &&
      (lower.includes('handshake') || lower.includes('failed') || lower.includes('error'))) {
    return { kind: 'proxy.reality_error', userMessage: 'VLESS Reality handshake failed — проверьте pbk/sid и fingerprint' }
  }
  if (lower.includes('invalid flow') || (lower.includes('xtls') && lower.includes('error'))) {
    return { kind: 'proxy.flow_error', userMessage: 'Неверный XTLS flow — требуется xtls-rprx-vision' }
  }
  if (lower.includes('certificate') || (lower.includes('tls') && lower.includes('verify'))) {
    return { kind: 'proxy.tls_error', userMessage: 'Ошибка TLS сертификата — проверьте SNI' }
  }
  if ((lower.includes('no such host') || lower.includes('dns lookup')) && lower.includes('error')) {
    return { kind: 'proxy.dns_error', userMessage: 'DNS не смог разрешить адрес сервера' }
  }
  if (lower.includes('connection refused')) {
    return { kind: 'proxy.connection_refused', userMessage: 'Сервер отклонил подключение — порт заблокирован' }
  }
  if (lower.includes('deadline exceeded') || lower.includes('timed out')) {
    return { kind: 'proxy.timeout', userMessage: 'Тайм-аут подключения к серверу' }
  }
  if ((lower.includes('tun') || lower.includes('wintun')) &&
      (lower.includes('access') || lower.includes('denied') || lower.includes('failed') || lower.includes('error'))) {
    return { kind: 'vpn.preflight_failed', userMessage: 'TUN адаптер: ошибка доступа — запустите приложение от имени администратора' }
  }
  return null
}

// ─── Health score ─────────────────────────────────────────────────────────────

function computeHealthScore(h: HealthStatus): number {
  if (!h.processAlive) return 0
  return (
    (h.processAlive   ? 25 : 0) +
    (h.apiResponding  ? 20 : 0) +
    (h.connectivityOk ? 20 : 0) +
    (h.dnsOk          ? 15 : 0) +
    (h.tunAvailable   ? 15 : 0) +
    (h.trafficActive  ? 5  : 0)
  )
}

// ─── State mapping ────────────────────────────────────────────────────────────

function engineStateToVpnState(state: RuntimeState): VPNConnectionState {
  switch (state) {
    case 'idle':         return 'disconnected'
    case 'starting':     return 'connecting'
    case 'running':      return 'connected'
    case 'stopping':     return 'disconnecting'
    case 'crashed':      return 'reconnecting'
    case 'reconnecting': return 'reconnecting'
    case 'error':        return 'error'
  }
}

// ─── Event factory ────────────────────────────────────────────────────────────

function makeEvent(
  kind: RuntimeEventKind,
  severity: RuntimeEventSeverity,
  message: string,
  metadata?: Record<string, unknown>
): RuntimeEvent {
  return {
    id: randomUUID(),
    kind,
    severity,
    timestamp: Date.now(),
    message,
    ...(metadata !== undefined ? { metadata } : {}),
  }
}

function classifyHealthDegradation(h: HealthStatus): RuntimeEventKind | null {
  if (!h.connectivityOk) return 'health.offline'
  if (!h.dnsOk) return 'health.dns_failure'
  if (!h.tunAvailable) return 'health.tunnel_unstable'
  const score = computeHealthScore(h)
  return score < 80 ? 'health.degraded' : null
}

// ─── Captive portal detection ─────────────────────────────────────────────────
// Passive: fires only when connectivity is already broken (no extra polling).

async function detectCaptivePortal(): Promise<boolean> {
  try {
    const res = await fetch('http://connectivitycheck.gstatic.com/generate_204', {
      method: 'GET',
      signal: AbortSignal.timeout(3000),
      redirect: 'manual',
    })
    // 204 = internet is working; anything else (redirect/200/etc.) = captive portal
    return res.status !== 204
  } catch {
    return false  // can't tell — assume no captive portal
  }
}

function buildSuggestion(
  h: HealthStatus,
  captivePortal: boolean | undefined,
  quarantinedNodes: number
): string | null {
  if (captivePortal) return 'Обнаружен captive portal — подключитесь к сети через браузер'
  if (!h.dnsOk) return 'DNS не работает — попробуйте сменить DNS-профиль'
  if (!h.tunAvailable) return 'TUN-адаптер недоступен — перезапустите приложение от имени администратора'
  if (quarantinedNodes > 0) return `${quarantinedNodes} узлов в карантине — попробуйте другой прокси`
  if (!h.connectivityOk) return 'Нет связи с сервером — проверьте настройки прокси или смените узел'
  return null
}

// ─── Config ───────────────────────────────────────────────────────────────────

export interface RuntimeServiceConfig {
  manager: RuntimeManager
  configSource?: ConfigSource
  getSettings: () => AppSettings
  apiPort?: number
  apiSecret?: string
  binaryPath?: string
  workingDir?: string
}

// ─── Implementation ───────────────────────────────────────────────────────────

export class RuntimeServiceImpl implements RuntimeService {
  private readonly manager: RuntimeManager
  private configSource: ConfigSource | undefined
  private readonly getSettings: () => AppSettings
  private readonly apiPort: number
  private readonly apiSecret: string
  private readonly binaryPath: string
  private readonly workingDir: string

  private currentMode: VPNMode = 'bypass'
  private connectedAt: number | null = null
  private lastError: string | null = null
  private lastHealthDegradation: RuntimeEventKind | null = null
  private activeProxy: string | null = null

  // Throttle error classification — don't spam the same error every log line
  private lastClassifiedErrorKind: string | null = null
  private lastClassifiedAt = 0

  // Mutex flags: prevent concurrent connect/disconnect operations
  private connectLock = false
  private disconnectLock = false

  setConfigSource(source: ConfigSource): void {
    this.configSource = source
  }

  constructor(config: RuntimeServiceConfig) {
    this.manager = config.manager
    this.configSource = config.configSource
    this.getSettings = config.getSettings
    this.apiPort = config.apiPort ?? VPN.MIHOMO_API_PORT
    this.apiSecret = config.apiSecret ?? ''
    this.binaryPath = config.binaryPath ?? ''
    this.workingDir = config.workingDir ?? ''

    this.manager.on('stateChanged', ({ state }) => {
      if (state === 'running') {
        this.connectedAt = Date.now()
        this.lastError = null
        this.lastClassifiedErrorKind = null
        enableSystemProxy('127.0.0.1', VPN.MIHOMO_MIXED_PORT)
        sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
          makeEvent('vpn.connected', 'info', 'VPN connected'))
        // Async: discover active proxy after engine is up
        this.refreshActiveProxy().catch(() => undefined)
        // Record success for active proxy
        if (this.activeProxy) {
          getNodeHealthManager().recordSuccess(this.activeProxy)
        }
      } else if (state === 'idle') {
        const wasConnected = this.connectedAt !== null
        this.connectedAt = null
        this.activeProxy = null
        disableSystemProxy()
        if (wasConnected) {
          sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
            makeEvent('vpn.disconnected', 'info', 'VPN disconnected'))
        }
      } else if (state === 'error') {
        this.connectedAt = null
        this.activeProxy = null
        sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
          makeEvent('vpn.error', 'error', this.lastError ?? 'VPN error'))
      } else if (state === 'reconnecting' || state === 'crashed') {
        sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
          makeEvent('reconnect.attempt', 'warning', 'Attempting reconnect', { state }))
      }
      sendToRenderer(IpcChannel.EVENT_VPN_STATUS, this.getStatus())
    })

    this.manager.on('trafficUpdate', ({ stats }) => {
      sendToRenderer(IpcChannel.EVENT_VPN_TRAFFIC, stats)
    })

    this.manager.on('error', ({ error, fatal }) => {
      this.lastError = error.message
      if (fatal) {
        sendToRenderer(IpcChannel.EVENT_VPN_ERROR, {
          code: 'FATAL_ENGINE_ERROR',
          message: error.message,
        })
        sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
          makeEvent('vpn.error', 'critical', error.message, { fatal: true }))
      }
    })

    this.manager.on('healthChanged', ({ health }) => {
      const payload: VpnHealthPayload = {
        processAlive: health.processAlive,
        apiResponding: health.apiResponding,
        connectivityOk: health.connectivityOk,
        dnsOk: health.dnsOk,
        trafficActive: health.trafficActive,
        tunAvailable: health.tunAvailable,
        checkedAt: health.checkedAt,
      }
      sendToRenderer(IpcChannel.EVENT_VPN_HEALTH, payload)

      const degradationKind = classifyHealthDegradation(health)
      if (degradationKind !== this.lastHealthDegradation) {
        if (degradationKind !== null) {
          sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
            makeEvent(degradationKind, 'warning', `Connection health degraded: ${degradationKind}`))
        } else if (this.lastHealthDegradation !== null) {
          sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
            makeEvent('health.recovered', 'info', 'Connection health recovered'))
        }
        this.lastHealthDegradation = degradationKind
      }
    })

    // Subscribe to Mihomo log output: forward to pino + classify for IPC events.
    // ProcessManager now parses the actual Mihomo level from the structured log line.
    this.manager.on('logLine', ({ level, message }) => {
      if (level === 'error') {
        getLogger().error({ from: 'mihomo' }, message)
      } else if (level === 'warn') {
        getLogger().warn({ from: 'mihomo' }, message)
      } else if (level === 'info') {
        getLogger().info({ from: 'mihomo' }, message)
      } else {
        return  // drop debug/trace
      }

      const classified = classifyMihomoLogLine_inner(message)
      if (!classified) return

      const now = Date.now()
      const isDuplicate =
        classified.kind === this.lastClassifiedErrorKind &&
        now - this.lastClassifiedAt < 10_000

      if (!isDuplicate) {
        this.lastClassifiedErrorKind = classified.kind
        this.lastClassifiedAt = now
        sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
          makeEvent(classified.kind, 'warning', classified.userMessage))

        // Record failure against the active proxy for node health tracking
        if (this.activeProxy) {
          getNodeHealthManager().recordFailure(this.activeProxy, classified.kind)
        }
      }
    })
  }

  // ── Pre-flight validation ──────────────────────────────────────────────────

  private async runPreflight(): Promise<void> {
    if (!this.binaryPath) return  // skip if path not configured (dev/test)

    const result = await validateRuntimeEnvironment({
      binaryPath: this.binaryPath,
      workingDir: this.workingDir,
      apiPort: this.apiPort,
    })

    const log = getLogger()

    for (const issue of result.issues) {
      log.warn({ code: issue.code }, `Preflight: ${issue.message}`)
      const severity: RuntimeEventSeverity = issue.fatal ? 'error' : 'warning'
      const kind: RuntimeEventKind = issue.fatal ? 'vpn.preflight_failed' : 'vpn.preflight_warn'
      sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
        makeEvent(kind, severity, issue.message, { code: issue.code }))
    }

    if (!result.ok) {
      const fatal = result.issues.find(i => i.fatal)
      throw new Error(fatal?.message ?? 'Runtime environment validation failed')
    }
  }

  // ── Engine profile composition (DNS + routing) ─────────────────────────────
  // Build the DnsProfile from current settings. RoutingPolicy is composed
  // later via RoutingScenarioService (A.3); for now returns undefined and
  // the engine falls back to legacy vpnMode-based rules.

  private buildDnsProfileForEngine(): DnsProfile {
    const settings = this.getSettings()
    return buildEngineDnsProfile(settings.dnsPreset, settings.customDnsProfile, settings.dnsStrategy)
  }

  private buildRoutingPolicyForEngine(): NormalizedPolicy | undefined {
    // The VPN mode is the master routing control: full/split fall through to the
    // engine's legacy vpnMode rules (policy undefined), bypass = Smart-Russia,
    // custom = the user's enabled scenarios.
    const policy = getRoutingScenarioService().composePolicyForMode(this.currentMode)
    return policy ?? undefined
  }

  // ── Subscription resolution (aggregator-first, legacy fallback) ────────────

  private async fetchSubscriptionYaml(): Promise<{ yaml: string; proxyCount: number; source: 'aggregator' | 'configSource' }> {
    const log = getLogger()
    const enabled = getSubscriptionStore().list().filter(e => e.enabled)

    if (enabled.length > 0) {
      try {
        const snapshot = await getSubscriptionAggregator().fetchAggregatedYaml()
        for (const w of snapshot.warnings) log.warn({ source: 'aggregator' }, w)
        return { yaml: snapshot.yaml, proxyCount: snapshot.totalProxies, source: 'aggregator' }
      } catch (err) {
        log.warn({ err }, 'Aggregator failed — falling back to legacy configSource')
      }
    }

    if (this.configSource) {
      const yaml = await this.configSource.fetchYaml()
      let proxyCount = 0
      try { proxyCount = normalizeSubscriptionContent(yaml).proxyCount } catch { /* keep 0 */ }
      return { yaml, proxyCount, source: 'configSource' }
    }

    throw new Error('No subscription configured — add one in Подписки tab or complete onboarding')
  }

  // ── Active proxy discovery ─────────────────────────────────────────────────

  private async refreshActiveProxy(): Promise<void> {
    if (!this.apiSecret) return

    for (const group of SELECT_GROUP_CANDIDATES) {
      try {
        const res = await fetch(
          `http://127.0.0.1:${this.apiPort}/proxies/${encodeURIComponent(group)}`,
          {
            headers: { Authorization: `Bearer ${this.apiSecret}` },
            signal: AbortSignal.timeout(3000),
          }
        )
        if (!res.ok) continue
        const data = await res.json() as { now?: string }
        if (data.now) {
          this.activeProxy = data.now
          sendToRenderer(IpcChannel.EVENT_VPN_STATUS, this.getStatus())
          sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
            makeEvent('proxy.selected', 'info', `Active proxy: ${data.now}`))
          return
        }
      } catch { /* try next group */ }
    }
  }

  // ── Public API ─────────────────────────────────────────────────────────────

  async connect(): Promise<void> {
    const state = this.manager.getState()
    if (state === 'running') return  // idempotent: already connected
    if (state === 'starting' || this.connectLock) {
      throw new Error('Connection already in progress')
    }

    // Either legacy configSource OR multi-subscription store must have something usable.
    const hasMultiSub = getSubscriptionStore().list().some(e => e.enabled)
    if (!this.configSource && !hasMultiSub) {
      throw new Error('No subscription configured. Add one in Подписки или complete onboarding.')
    }

    this.connectLock = true
    const log = getLogger()
    try {
      await this.runPreflight()

      const settings = this.getSettings()
      this.currentMode = settings.vpnMode

      const { yaml: subscriptionYaml, proxyCount, source } = await this.fetchSubscriptionYaml()

      if (proxyCount === 0) {
        const msg = 'Subscription has no usable proxies. Check your config source in settings.'
        sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
          makeEvent('vpn.preflight_failed', 'error', msg, { code: 'NO_PROXIES' }))
        throw new Error(msg)
      }

      log.info({ proxyCount, source }, 'Subscription resolved before connect')

      const selectedProxy = settings.selectedProxy ?? undefined
      const splitProcessList = settings.splitProcessList ?? []
      const dnsProfile = this.buildDnsProfileForEngine()
      const routingPolicy = this.buildRoutingPolicyForEngine()

      await this.manager.connect({
        subscriptionYaml,
        vpnMode: this.currentMode,
        ...(selectedProxy ? { selectedProxy } : {}),
        generatorSettings: {
          ...DEFAULT_GENERATOR_SETTINGS,
          ...(this.currentMode === 'split' ? { splitTunnelProcesses: splitProcessList } : {}),
        },
        dnsProfile,
        ...(routingPolicy ? { routingPolicy } : {}),
        utlsFingerprint: settings.utlsFingerprint ?? 'randomized',
      })
    } finally {
      this.connectLock = false
    }
  }

  async disconnect(): Promise<void> {
    const state = this.manager.getState()
    if (state === 'idle') return  // idempotent: already disconnected
    if (this.disconnectLock) return  // already disconnecting
    this.disconnectLock = true
    try {
      await this.manager.disconnect('intentional')
    } finally {
      this.disconnectLock = false
    }
  }

  getStatus(): VPNStatus {
    const state = this.manager.getState()
    const health = this.manager.getHealth()
    return {
      ...INITIAL_VPN_STATUS,
      state: engineStateToVpnState(state),
      mode: this.currentMode,
      connectedAt: this.connectedAt,
      lastError: this.lastError,
      ...(this.activeProxy ? { activeProxy: this.activeProxy } : {}),
      ...(health.checkedAt ? { engineHealthScore: computeHealthScore(health) } : {}),
    }
  }

  async setMode(mode: VPNMode): Promise<void> {
    this.currentMode = mode

    if (this.manager.getState() === 'running') {
      const settings = this.getSettings()
      const dnsProfile = this.buildDnsProfileForEngine()
      const routingPolicy = this.buildRoutingPolicyForEngine()
      const { yaml } = await this.fetchSubscriptionYaml()
      await this.manager.updateProfile({
        subscriptionYaml: yaml,
        vpnMode: mode,
        ...(this.activeProxy ? { selectedProxy: this.activeProxy } : {}),
        generatorSettings: {
          ...DEFAULT_GENERATOR_SETTINGS,
          ...(mode === 'split' ? { splitTunnelProcesses: settings.splitProcessList ?? [] } : {}),
        },
        dnsProfile,
        ...(routingPolicy ? { routingPolicy } : {}),
        utlsFingerprint: settings.utlsFingerprint ?? 'randomized',
      })
    }
  }

  getEngineVersion(): string | null {
    return this.manager.getEngineVersion()
  }

  async getConnectivity(): Promise<VPNConnectivityInfo | null> {
    const state = this.manager.getState()
    const health = this.manager.getHealth()

    let activeProxy: string | null = this.activeProxy
    let proxyCount = 0

    if (state === 'running' && health.apiResponding && this.apiSecret) {
      // Refresh active proxy
      for (const group of SELECT_GROUP_CANDIDATES) {
        try {
          const res = await fetch(
            `http://127.0.0.1:${this.apiPort}/proxies/${encodeURIComponent(group)}`,
            {
              headers: { Authorization: `Bearer ${this.apiSecret}` },
              signal: AbortSignal.timeout(3000),
            }
          )
          if (!res.ok) continue
          const data = await res.json() as { now?: string; all?: string[] }
          if (data.now) activeProxy = data.now
          if (data.all) proxyCount = data.all.length
          break
        } catch { /* try next */ }
      }
    }

    // Captive portal detection: check for redirect on plain HTTP
    let captivePortal: boolean | undefined
    if (state === 'running' && !health.connectivityOk) {
      captivePortal = await detectCaptivePortal()
    }

    const quarantinedNodes = getNodeHealthManager().getQuarantinedNodes().length
    const healthScore = computeHealthScore(health)

    const suggestion = buildSuggestion(health, captivePortal, quarantinedNodes)

    // Determine Reality/TLS status for the active proxy
    let realityStatus: 'reality' | 'tls' | 'none' = 'none'
    if (activeProxy && state === 'running') {
      try {
        const entries = await getConfigSourceService().getServerList()
        const entry = entries.find(e => e.name === activeProxy)
        if (entry?.securityType === 'reality') realityStatus = 'reality'
        else if (entry?.securityType === 'tls') realityStatus = 'tls'
      } catch { /* non-fatal */ }
    }

    const apiUrl = state === 'running' ? `http://127.0.0.1:${this.apiPort}` : undefined

    return {
      engineState: state,
      processAlive: health.processAlive,
      apiResponding: health.apiResponding,
      tunAvailable: health.tunAvailable,
      connectivityOk: health.connectivityOk,
      dnsOk: health.dnsOk,
      trafficActive: health.trafficActive,
      activeProxy,
      proxyCount,
      healthScore,
      checkedAt: health.checkedAt > 0 ? health.checkedAt : Date.now(),
      ...(captivePortal !== undefined ? { captivePortal } : {}),
      ...(quarantinedNodes > 0 ? { quarantinedNodes } : {}),
      ...(suggestion ? { suggestion } : {}),
      realityStatus,
      ...(apiUrl ? { apiUrl } : {}),
    }
  }

  getState(): string {
    return this.manager.getState()
  }

  async probeProxyLatency(tag: string, testUrl: string, timeoutMs: number): Promise<number | null> {
    if (this.manager.getState() !== 'running') return null
    return this.manager.probeLatency(tag, testUrl, timeoutMs)
  }

  async setSelectedProxy(proxyName: string): Promise<void> {
    if (this.manager.getState() !== 'running') {
      throw new Error('Cannot change proxy: VPN is not running')
    }

    const settings = this.getSettings()
    const dnsProfile = this.buildDnsProfileForEngine()
    const routingPolicy = this.buildRoutingPolicyForEngine()
    const { yaml } = await this.fetchSubscriptionYaml()

    await this.manager.updateProfile({
      subscriptionYaml: yaml,
      vpnMode: this.currentMode,
      selectedProxy: proxyName,
      generatorSettings: {
        ...DEFAULT_GENERATOR_SETTINGS,
        ...(this.currentMode === 'split' ? { splitTunnelProcesses: settings.splitProcessList ?? [] } : {}),
      },
      dnsProfile,
      ...(routingPolicy ? { routingPolicy } : {}),
      utlsFingerprint: settings.utlsFingerprint ?? 'randomized',
    })
    this.activeProxy = proxyName
    sendToRenderer(IpcChannel.EVENT_VPN_STATUS, this.getStatus())
    sendToRenderer(IpcChannel.EVENT_PROXY_CHANGED, proxyName)
    sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
      makeEvent('proxy.selected', 'info', `Proxy changed to: ${proxyName}`))
  }

  // Called by SubscriptionsHandler after add/update/remove/refresh while VPN is running.
  // Triggers a hot-reload through manager.updateProfile so the engine picks up the
  // newly aggregated YAML. No-op when disconnected.
  async notifySubscriptionsChanged(): Promise<void> {
    if (this.manager.getState() !== 'running') return
    const log = getLogger()
    try {
      const settings = this.getSettings()
      const dnsProfile = this.buildDnsProfileForEngine()
      const routingPolicy = this.buildRoutingPolicyForEngine()
      const { yaml, proxyCount, source } = await this.fetchSubscriptionYaml()
      if (proxyCount === 0) {
        log.warn({ source }, 'Subscription hot-reload: empty proxy list — skipping')
        return
      }
      await this.manager.updateProfile({
        subscriptionYaml: yaml,
        vpnMode: this.currentMode,
        ...(this.activeProxy ? { selectedProxy: this.activeProxy } : {}),
        generatorSettings: {
          ...DEFAULT_GENERATOR_SETTINGS,
          ...(this.currentMode === 'split' ? { splitTunnelProcesses: settings.splitProcessList ?? [] } : {}),
        },
        dnsProfile,
        ...(routingPolicy ? { routingPolicy } : {}),
        utlsFingerprint: settings.utlsFingerprint ?? 'randomized',
      })
      log.info({ proxyCount, source }, 'Subscription hot-reload applied')
    } catch (err) {
      log.warn({ err }, 'Subscription hot-reload failed')
    }
  }

  // ── Active connections (Mihomo /connections) ──────────────────────────────

  async getConnections(): Promise<import('../../../shared/ipc/types').ActiveConnectionsSnapshot | null> {
    const info = await this.manager.getConnections()
    if (!info) return null

    const connections = info.connections.map(c => {
      const meta = c.metadata
      const chain = c.chains[0] ?? 'DIRECT'  // mihomo prepends final hop
      const process = meta.process ?? (meta.processPath ? meta.processPath.split(/[\\/]/).pop() : undefined)
      return {
        id: c.id,
        host: meta.host || meta.destinationIP || '—',
        network: meta.network ?? 'tcp',
        type: meta.type ?? '',
        destinationIP: meta.destinationIP ?? '',
        destinationPort: meta.destinationPort ?? '',
        sourceIP: meta.sourceIP ?? '',
        sourcePort: meta.sourcePort ?? '',
        ...(process ? { process } : {}),
        chain,
        rule: c.rule ?? '',
        upload: c.upload,
        download: c.download,
        start: c.start,
      }
    })

    return {
      uploadTotal: info.uploadTotal,
      downloadTotal: info.downloadTotal,
      count: connections.length,
      connections,
      fetchedAt: Date.now(),
    }
  }

  async closeConnection(id: string): Promise<void> {
    await this.manager.closeConnection(id)
  }

  async getProxyList(): Promise<import('../../../shared/ipc/types').ProxyEntry[]> {
    if (!this.configSource) return []
    try {
      const entries = await getConfigSourceService().getServerList()
      return entries.map(e => ({
        name: e.name,
        type: e.proxyProtocol,
        server: e.server,
        ...(e.port !== undefined ? { port: e.port } : {}),
        ...(e.transport ? { transport: e.transport } : {}),
        ...(e.securityType ? { security: e.securityType } : {}),
      }))
    } catch {
      return []
    }
  }

  dispose(): Promise<void> {
    return this.manager.dispose()
  }
}
