import { randomUUID } from 'crypto'
import { VPN, INITIAL_VPN_STATUS } from '@slave-vpn/shared'
import type { VPNStatus, VPNMode, VPNConnectionState } from '@slave-vpn/shared'
import { RuntimeManager } from '@slave-vpn/runtime'
import type { RuntimeState, HealthStatus } from '@slave-vpn/runtime'
import type { ConfigSource } from '@slave-vpn/provider'
import type { RuntimeService } from '../RuntimeService'
import type {
  AppSettings,
  RuntimeEvent,
  RuntimeEventKind,
  RuntimeEventSeverity,
  VpnHealthPayload,
  VPNConnectivityInfo,
} from '../../../shared/ipc/types'
import { IpcChannel } from '../../../shared/ipc/channels'
import { sendToRenderer } from '../../window'
import { validateRuntimeEnvironment } from './RuntimeEnvironmentValidator'
import { getNodeHealthManager } from '../NodeHealthManager'
import { getConfigSourceService } from './ConfigSourceService'
import { getLogger } from '../../logger'
import { normalizeSubscriptionContent } from '@slave-vpn/config'

// ─── Mihomo API group names (generated by config package) ────────────────────
// config package uses SLAVE-SELECT; mihomoYaml.ts uses SLAVE — check both.
const SELECT_GROUP_CANDIDATES = ['SLAVE-SELECT', 'SLAVE']

const DEFAULT_GENERATOR_SETTINGS = {
  tunEnabled: true,
  tunStack: 'mixed' as const,
  fakeIpEnabled: true,
  dnsOverHttps: 'https://8.8.8.8/dns-query',
  fallbackDns: ['8.8.8.8', '8.8.4.4'],
  mixedPort: VPN.MIHOMO_MIXED_PORT,
}

// ─── Error classifier for Mihomo log output ───────────────────────────────────

function classifyMihomoLogLine_inner(line: string): { kind: RuntimeEventKind; userMessage: string } | null {
  const lower = line.toLowerCase()

  if ((lower.includes('reality') || lower.includes('utls')) &&
      (lower.includes('handshake') || lower.includes('failed') || lower.includes('error'))) {
    return { kind: 'proxy.reality_error', userMessage: 'VLESS Reality handshake failed — проверьте pbk/sid и fingerprint' }
  }
  if (lower.includes('invalid flow') || (lower.includes('xtls') && lower.includes('error'))) {
    return { kind: 'proxy.flow_error', userMessage: 'Неверный XTLS flow — требуется xtls-rprx-vision' }
  }
  if (lower.includes('certificate') || (lower.includes('tls') && lower.includes('verify'))) {
    return { kind: 'proxy.tls_error', userMessage: 'Ошибка TLS сертификата — проверьте SNI' }
  }
  if ((lower.includes('no such host') || lower.includes('dns lookup')) && lower.includes('error')) {
    return { kind: 'proxy.dns_error', userMessage: 'DNS не смог разрешить адрес сервера' }
  }
  if (lower.includes('connection refused')) {
    return { kind: 'proxy.connection_refused', userMessage: 'Сервер отклонил подключение — порт заблокирован' }
  }
  if (lower.includes('deadline exceeded') || lower.includes('timed out')) {
    return { kind: 'proxy.timeout', userMessage: 'Тайм-аут подключения к серверу' }
  }
  return null
}

// ─── Health score ─────────────────────────────────────────────────────────────

function computeHealthScore(h: HealthStatus): number {
  if (!h.processAlive) return 0
  return (
    (h.processAlive   ? 25 : 0) +
    (h.apiResponding  ? 20 : 0) +
    (h.connectivityOk ? 20 : 0) +
    (h.dnsOk          ? 15 : 0) +
    (h.tunAvailable   ? 15 : 0) +
    (h.trafficActive  ? 5  : 0)
  )
}

// ─── State mapping ────────────────────────────────────────────────────────────

function engineStateToVpnState(state: RuntimeState): VPNConnectionState {
  switch (state) {
    case 'idle':         return 'disconnected'
    case 'starting':     return 'connecting'
    case 'running':      return 'connected'
    case 'stopping':     return 'disconnecting'
    case 'crashed':      return 'reconnecting'
    case 'reconnecting': return 'reconnecting'
    case 'error':        return 'error'
  }
}

// ─── Event factory ────────────────────────────────────────────────────────────

function makeEvent(
  kind: RuntimeEventKind,
  severity: RuntimeEventSeverity,
  message: string,
  metadata?: Record<string, unknown>
): RuntimeEvent {
  return {
    id: randomUUID(),
    kind,
    severity,
    timestamp: Date.now(),
    message,
    ...(metadata !== undefined ? { metadata } : {}),
  }
}

function classifyHealthDegradation(h: HealthStatus): RuntimeEventKind | null {
  if (!h.connectivityOk) return 'health.offline'
  if (!h.dnsOk) return 'health.dns_failure'
  if (!h.tunAvailable) return 'health.tunnel_unstable'
  const score = computeHealthScore(h)
  return score < 80 ? 'health.degraded' : null
}

// ─── Captive portal detection ─────────────────────────────────────────────────
// Passive: fires only when connectivity is already broken (no extra polling).

async function detectCaptivePortal(): Promise<boolean> {
  try {
    const res = await fetch('http://connectivitycheck.gstatic.com/generate_204', {
      method: 'GET',
      signal: AbortSignal.timeout(3000),
      redirect: 'manual',
    })
    // 204 = internet is working; anything else (redirect/200/etc.) = captive portal
    return res.status !== 204
  } catch {
    return false  // can't tell — assume no captive portal
  }
}

function buildSuggestion(
  h: HealthStatus,
  captivePortal: boolean | undefined,
  quarantinedNodes: number
): string | null {
  if (captivePortal) return 'Обнаружен captive portal — подключитесь к сети через браузер'
  if (!h.dnsOk) return 'DNS не работает — попробуйте сменить DNS-профиль'
  if (!h.tunAvailable) return 'TUN-адаптер недоступен — перезапустите приложение от имени администратора'
  if (quarantinedNodes > 0) return `${quarantinedNodes} узлов в карантине — попробуйте другой прокси`
  if (!h.connectivityOk) return 'Нет связи с сервером — проверьте настройки прокси или смените узел'
  return null
}

// ─── Config ───────────────────────────────────────────────────────────────────

export interface RuntimeServiceConfig {
  manager: RuntimeManager
  configSource?: ConfigSource
  getSettings: () => AppSettings
  apiPort?: number
  apiSecret?: string
  binaryPath?: string
  workingDir?: string
}

// ─── Implementation ───────────────────────────────────────────────────────────

export class RuntimeServiceImpl implements RuntimeService {
  private readonly manager: RuntimeManager
  private configSource: ConfigSource | undefined
  private readonly getSettings: () => AppSettings
  private readonly apiPort: number
  private readonly apiSecret: string
  private readonly binaryPath: string
  private readonly workingDir: string

  private currentMode: VPNMode = 'bypass'
  private connectedAt: number | null = null
  private lastError: string | null = null
  private lastHealthDegradation: RuntimeEventKind | null = null
  private activeProxy: string | null = null

  // Throttle error classification — don't spam the same error every log line
  private lastClassifiedErrorKind: string | null = null
  private lastClassifiedAt = 0

  // Mutex flags: prevent concurrent connect/disconnect operations
  private connectLock = false
  private disconnectLock = false

  setConfigSource(source: ConfigSource): void {
    this.configSource = source
  }

  constructor(config: RuntimeServiceConfig) {
    this.manager = config.manager
    this.configSource = config.configSource
    this.getSettings = config.getSettings
    this.apiPort = config.apiPort ?? VPN.MIHOMO_API_PORT
    this.apiSecret = config.apiSecret ?? ''
    this.binaryPath = config.binaryPath ?? ''
    this.workingDir = config.workingDir ?? ''

    this.manager.on('stateChanged', ({ state }) => {
      if (state === 'running') {
        this.connectedAt = Date.now()
        this.lastError = null
        this.lastClassifiedErrorKind = null
        sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
          makeEvent('vpn.connected', 'info', 'VPN connected'))
        // Async: discover active proxy after engine is up
        this.refreshActiveProxy().catch(() => undefined)
        // Record success for active proxy
        if (this.activeProxy) {
          getNodeHealthManager().recordSuccess(this.activeProxy)
        }
      } else if (state === 'idle') {
        const wasConnected = this.connectedAt !== null
        this.connectedAt = null
        this.activeProxy = null
        if (wasConnected) {
          sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
            makeEvent('vpn.disconnected', 'info', 'VPN disconnected'))
        }
      } else if (state === 'error') {
        this.connectedAt = null
        this.activeProxy = null
        sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
          makeEvent('vpn.error', 'error', this.lastError ?? 'VPN error'))
      } else if (state === 'reconnecting' || state === 'crashed') {
        sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
          makeEvent('reconnect.attempt', 'warning', 'Attempting reconnect', { state }))
      }
      sendToRenderer(IpcChannel.EVENT_VPN_STATUS, this.getStatus())
    })

    this.manager.on('trafficUpdate', ({ stats }) => {
      sendToRenderer(IpcChannel.EVENT_VPN_TRAFFIC, stats)
    })

    this.manager.on('error', ({ error, fatal }) => {
      this.lastError = error.message
      if (fatal) {
        sendToRenderer(IpcChannel.EVENT_VPN_ERROR, {
          code: 'FATAL_ENGINE_ERROR',
          message: error.message,
        })
        sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
          makeEvent('vpn.error', 'critical', error.message, { fatal: true }))
      }
    })

    this.manager.on('healthChanged', ({ health }) => {
      const payload: VpnHealthPayload = {
        processAlive: health.processAlive,
        apiResponding: health.apiResponding,
        connectivityOk: health.connectivityOk,
        dnsOk: health.dnsOk,
        trafficActive: health.trafficActive,
        tunAvailable: health.tunAvailable,
        checkedAt: health.checkedAt,
      }
      sendToRenderer(IpcChannel.EVENT_VPN_HEALTH, payload)

      const degradationKind = classifyHealthDegradation(health)
      if (degradationKind !== this.lastHealthDegradation) {
        if (degradationKind !== null) {
          sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
            makeEvent(degradationKind, 'warning', `Connection health degraded: ${degradationKind}`))
        } else if (this.lastHealthDegradation !== null) {
          sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
            makeEvent('health.recovered', 'info', 'Connection health recovered'))
        }
        this.lastHealthDegradation = degradationKind
      }
    })

    // Subscribe to Mihomo log output for error classification
    this.manager.on('logLine', ({ level, message }) => {
      if (level !== 'error' && level !== 'warn') return
      const classified = classifyMihomoLogLine_inner(message)
      if (!classified) return

      const now = Date.now()
      const isDuplicate =
        classified.kind === this.lastClassifiedErrorKind &&
        now - this.lastClassifiedAt < 10_000

      if (!isDuplicate) {
        this.lastClassifiedErrorKind = classified.kind
        this.lastClassifiedAt = now
        sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
          makeEvent(classified.kind, 'warning', classified.userMessage))

        // Record failure against the active proxy for node health tracking
        if (this.activeProxy) {
          getNodeHealthManager().recordFailure(this.activeProxy, classified.kind)
        }
      }
    })
  }

  // ── Pre-flight validation ──────────────────────────────────────────────────

  private async runPreflight(): Promise<void> {
    if (!this.binaryPath) return  // skip if path not configured (dev/test)

    const result = await validateRuntimeEnvironment({
      binaryPath: this.binaryPath,
      workingDir: this.workingDir,
      apiPort: this.apiPort,
    })

    const log = getLogger()

    for (const issue of result.issues) {
      log.warn({ code: issue.code }, `Preflight: ${issue.message}`)
      const severity: RuntimeEventSeverity = issue.fatal ? 'error' : 'warning'
      const kind: RuntimeEventKind = issue.fatal ? 'vpn.preflight_failed' : 'vpn.preflight_warn'
      sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
        makeEvent(kind, severity, issue.message, { code: issue.code }))
    }

    if (!result.ok) {
      const fatal = result.issues.find(i => i.fatal)
      throw new Error(fatal?.message ?? 'Runtime environment validation failed')
    }
  }

  // ── Active proxy discovery ─────────────────────────────────────────────────

  private async refreshActiveProxy(): Promise<void> {
    if (!this.apiSecret) return

    for (const group of SELECT_GROUP_CANDIDATES) {
      try {
        const res = await fetch(
          `http://127.0.0.1:${this.apiPort}/proxies/${encodeURIComponent(group)}`,
          {
            headers: { Authorization: `Bearer ${this.apiSecret}` },
            signal: AbortSignal.timeout(3000),
          }
        )
        if (!res.ok) continue
        const data = await res.json() as { now?: string }
        if (data.now) {
          this.activeProxy = data.now
          sendToRenderer(IpcChannel.EVENT_VPN_STATUS, this.getStatus())
          sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
            makeEvent('proxy.selected', 'info', `Active proxy: ${data.now}`))
          return
        }
      } catch { /* try next group */ }
    }
  }

  // ── Public API ─────────────────────────────────────────────────────────────

  async connect(): Promise<void> {
    const state = this.manager.getState()
    if (state === 'running') return  // idempotent: already connected
    if (state === 'starting' || this.connectLock) {
      throw new Error('Connection already in progress')
    }

    if (!this.configSource) {
      throw new Error('No config source configured. Complete onboarding first.')
    }

    this.connectLock = true
    const log = getLogger()
    try {
      await this.runPreflight()

      const settings = this.getSettings()
      this.currentMode = settings.vpnMode

      const subscriptionYaml = await this.configSource.fetchYaml()

      // Validate subscription has usable proxies before starting engine
      let proxyCount = 0
      try {
        const result = normalizeSubscriptionContent(subscriptionYaml)
        proxyCount = result.proxyCount
      } catch { /* count stays 0 */ }

      if (proxyCount === 0) {
        const msg = 'Subscription has no usable proxies. Check your config source in settings.'
        sendToRenderer(IpcChannel.EVENT_RUNTIME_EVENT,
          makeEvent('vpn.preflight_failed', 'error', msg, { code: 'NO_PROXIES' }))
        throw new Error(msg)
      }

      log.info({ proxyCount }, 'Subscription validated before connect')

      await this.manager.connect({
        subscriptionYaml,
        vpnMode: this.currentMode,
        generatorSettings: {
          ...DEFAULT_GENERATOR_SETTINGS,
          ...(this.currentMode === 'split' ? { splitTunnelProcesses: [] } : {}),
        },
      })
    } finally {
      this.connectLock = false
    }
  }

  async disconnect(): Promise<void> {
    const state = this.manager.getState()
    if (state === 'idle') return  // idempotent: already disconnected
    if (this.disconnectLock) return  // already disconnecting
    this.disconnectLock = true
    try {
      await this.manager.disconnect('intentional')
    } finally {
      this.disconnectLock = false
    }
  }

  getStatus(): VPNStatus {
    const state = this.manager.getState()
    const health = this.manager.getHealth()
    return {
      ...INITIAL_VPN_STATUS,
      state: engineStateToVpnState(state),
      mode: this.currentMode,
      connectedAt: this.connectedAt,
      lastError: this.lastError,
      ...(this.activeProxy ? { activeProxy: this.activeProxy } : {}),
      ...(health.checkedAt ? { engineHealthScore: computeHealthScore(health) } : {}),
    }
  }

  async setMode(mode: VPNMode): Promise<void> {
    this.currentMode = mode

    if (this.manager.getState() === 'running' && this.configSource) {
      await this.manager.updateProfile({
        subscriptionYaml: await this.configSource.fetchYaml(),
        vpnMode: mode,
        generatorSettings: {
          ...DEFAULT_GENERATOR_SETTINGS,
          ...(mode === 'split' ? { splitTunnelProcesses: [] } : {}),
        },
      })
    }
  }

  getEngineVersion(): string | null {
    return this.manager.getEngineVersion()
  }

  async getConnectivity(): Promise<VPNConnectivityInfo | null> {
    const state = this.manager.getState()
    const health = this.manager.getHealth()

    let activeProxy: string | null = this.activeProxy
    let proxyCount = 0

    if (state === 'running' && health.apiResponding && this.apiSecret) {
      // Refresh active proxy
      for (const group of SELECT_GROUP_CANDIDATES) {
        try {
          const res = await fetch(
            `http://127.0.0.1:${this.apiPort}/proxies/${encodeURIComponent(group)}`,
            {
              headers: { Authorization: `Bearer ${this.apiSecret}` },
              signal: AbortSignal.timeout(3000),
            }
          )
          if (!res.ok) continue
          const data = await res.json() as { now?: string; all?: string[] }
          if (data.now) activeProxy = data.now
          if (data.all) proxyCount = data.all.length
          break
        } catch { /* try next */ }
      }
    }

    // Captive portal detection: check for redirect on plain HTTP
    let captivePortal: boolean | undefined
    if (state === 'running' && !health.connectivityOk) {
      captivePortal = await detectCaptivePortal()
    }

    const quarantinedNodes = getNodeHealthManager().getQuarantinedNodes().length
    const healthScore = computeHealthScore(health)

    const suggestion = buildSuggestion(health, captivePortal, quarantinedNodes)

    // Determine Reality/TLS status for the active proxy
    let realityStatus: 'reality' | 'tls' | 'none' = 'none'
    if (activeProxy && state === 'running') {
      try {
        const entries = await getConfigSourceService().getServerList()
        const entry = entries.find(e => e.name === activeProxy)
        if (entry?.securityType === 'reality') realityStatus = 'reality'
        else if (entry?.securityType === 'tls') realityStatus = 'tls'
      } catch { /* non-fatal */ }
    }

    const apiUrl = state === 'running' ? `http://127.0.0.1:${this.apiPort}` : undefined

    return {
      engineState: state,
      processAlive: health.processAlive,
      apiResponding: health.apiResponding,
      tunAvailable: health.tunAvailable,
      connectivityOk: health.connectivityOk,
      dnsOk: health.dnsOk,
      trafficActive: health.trafficActive,
      activeProxy,
      proxyCount,
      healthScore,
      checkedAt: health.checkedAt > 0 ? health.checkedAt : Date.now(),
      ...(captivePortal !== undefined ? { captivePortal } : {}),
      ...(quarantinedNodes > 0 ? { quarantinedNodes } : {}),
      ...(suggestion ? { suggestion } : {}),
      realityStatus,
      ...(apiUrl ? { apiUrl } : {}),
    }
  }

  getState(): string {
    return this.manager.getState()
  }

  async probeProxyLatency(tag: string, testUrl: string, timeoutMs: number): Promise<number | null> {
    if (this.manager.getState() !== 'running') return null
    return this.manager.probeLatency(tag, testUrl, timeoutMs)
  }

  dispose(): Promise<void> {
    return this.manager.dispose()
  }
}
